name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Setup deno version
      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.117.0

      - name: Test
        env:
          HOSTNAME: smtp.gmail.com
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO_USER: ${{ secrets.MAIL_USER }}
        run: deno run --allow-net --allow-env ./test.ts
